language: R
cache: packages
sudo: false

r_github_packages:
  - OHDSI/DatabaseConnector
  - OHDSI/FeatureExtraction
  - OHDSI/OhdsiRTools
  - OHDSI/BigKnn

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - export LD_LIBRARY_PATH=$JAVA_HOME:$LD_LIBRARY_PATH

notifications:
  recipients:
  - msuchard@gmail.com
  - schuemie@ohdsi.org
  - p.rijnbeek@erasmusmc.nl
  - jreps@its.jnj.com
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
    secure: pEhWT0SZmEpxcK0iclaqIro0HfU9gI555/dxaGm4h6lbJnZOJLTv19o65EV52HJRpTXtuv612bR7jf5+eOIqIkcrzO9XdbLMigp/R/YHkp22RFEZBnnGX9xH/3D6QbeeUaHn0h8goBildzX5q1ZyCVNBIpA7kP418b2pG3rWgaA=
    