language: R
cache: packages
sudo: false

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Adding dependencies into r-reticulate environment 
  - conda create -q -n r-reticulate   
  - conda install --name r-reticulate numpy 
  - conda install --name r-reticulate scipy
  - conda install --name r-reticulate scikit-learn
  - conda install --name r-reticulate pandas
  - conda install --name r-reticulate pydotplus
  - conda install --name r-reticulate -c conda-forge keras
  - conda install --name r-reticulate -c conda-forge tensorflow
  - conda install --name r-reticulate -c sebp scikit-survival
  - conda activate r-reticulate

branches:
  except:
    - /^*-v[0-9]/

r_packages:
  - covr
  - drat

r_github_packages:
  - OHDSI/DatabaseConnector
  - OHDSI/FeatureExtraction
  - OHDSI/OhdsiRTools
  - OHDSI/Cyclops
  - OHDSI/BigKnn
  - OHDSI/OhdsiSharing

before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

script:
  - R CMD build .
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --as-cran
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

after_success:
  - Rscript -e 'covr::codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && perl compare_versions --tag && bash deploy.sh && curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/

notifications:
  recipients:
  - msuchard@gmail.com
  - schuemie@ohdsi.org
  - p.rijnbeek@erasmusmc.nl
  - jreps@its.jnj.com
  email:
    on_success: change
    on_failure: change
